### ISSUE TITLE
Using message to handle multi service start

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/bridger#227]
https://github.com/darwinia-network/bridger/pull/226#pullrequestreview-722482602

**Comment by fewensa** [comment]
The problem here is that I hope the service will start other services. we must wait until the [task](https://github.com/darwinia-network/bridger/blob/b2316d4de0150770f926214b8b3962716fea77b8/task/task-darwinia-ethereum/src/task.rs#L55) is [saved](https://github.com/darwinia-network/bridger/blob/b2316d4de0150770f926214b8b3962716fea77b8/bin/src/route/task_manager.rs#L144) to [get it in the service](https://github.com/darwinia-network/bridger/blob/b2316d4de0150770f926214b8b3962716fea77b8/task/task-darwinia-ethereum/src/service/starter.rs#L72-L73).
If the service execution occurs before the save, the task cannot be obtained.

Currently using delay can solve this problem, but this is indeed caused by design, the next refactor will not have this problem. follow #267
